package br.ufg.inf.mestrado.hermeswidget.ontologies;
 
import com.hp.hpl.jena.ontology.Individual;
import com.hp.hpl.jena.ontology.OntModel;
import com.hp.hpl.jena.ontology.OntModelSpec;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Resource;
 
/**
 * Vocabulary definitions from quantitykind.ttl 
 * @author Auto-generated by schemagen on 06 nov 2019 14:48 
 */
public class QuantityKind {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static final OntModel M_MODEL = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://qudt.org/2.1/vocab/quantitykind#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );
  
    //Individual http://qudt.org/schema/quantitykind/RelativeHumidity
    public static final Individual RelativeHumidity = M_MODEL.createIndividual(NS + "RelativeHumidity", QUDT.QuantityKind);
    
    //Individual http://qudt.org/schema/quantitykind/CelsiusTemperature
    public static final Individual CelsiusTemperature = M_MODEL.createIndividual(NS + "CelsiusTemperature", QUDT.QuantityKind);
    
    //Individual http://qudt.org/schema/quantitykind/CO2Concentration
    public static final Individual CO2Concentration = M_MODEL.createIndividual(NS + "CO2Concentration", QUDT.QuantityKind);
    
    //Individual http://qudt.org/schema/quantitykind/TVOC
    public static final Individual TVOC = M_MODEL.createIndividual(NS + "TVOC", QUDT.QuantityKind);
    
}
