package br.ufg.inf.mestrado.hermeswidget.ontologies;
 
import com.hp.hpl.jena.ontology.ObjectProperty;
import com.hp.hpl.jena.ontology.OntClass;
import com.hp.hpl.jena.ontology.OntModel;
import com.hp.hpl.jena.ontology.OntModelSpec;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Resource;
 
 
/**
 * Vocabulary definitions from qudt.ttl 
 * @author Auto-generated by schemagen on 06 nov 2019 14:46 
 */
public class Qudt {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static final OntModel M_MODEL = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://qudt.org/2.1/schema/qudt#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );
    
    
    
    //Class http_//qudt.org/schema/qudt/QuantityKind
    public static final OntClass QuantityKind = M_MODEL.createClass("http://qudt.org/schema/qudt/QuantityKind");

    //Object Property http_//qudt.org/schema/qudt/TemperatureUnit
    public static final OntClass TemperatureUnit = M_MODEL.createClass("http://qudt.org/schema/qudt/TemperatureUnit");
    
    //Object Property http_//qudt.org/schema/qudt/DimensionlessUnit
    public static final OntClass DimensionlessUnit = M_MODEL.createClass("http://qudt.org/schema/qudt/DimensionlessUnit");
   
    
    //Object Property http_//qudt.org/schema/qudt/hasQuantityKind
    public static final ObjectProperty hasQuantityKind = M_MODEL.createObjectProperty("http://qudt.org/schema/qudt/hasQuantityKind");
    
    //Object Property http_//qudt.org/schema/qudt/hasUnit
    public static final ObjectProperty hasUnit = M_MODEL.createObjectProperty("http://qudt.org/schema/qudt/hasUnit");

    //Object Property http_//qudt.org/schema/qudt/unit
    public static final ObjectProperty Unit = M_MODEL.createObjectProperty("http://qudt.org/schema/qudt/unit");

    
}
