package br.ufg.inf.mestrado.hermeswidget.ontologies;

import com.hp.hpl.jena.ontology.AnnotationProperty;
import com.hp.hpl.jena.ontology.OntClass;
import com.hp.hpl.jena.ontology.OntModel;
import com.hp.hpl.jena.ontology.OntModelSpec;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Resource;

/**
 * Vocabulary definitions from symp.owl 
 * @author Auto-generated by schemagen on 02 mar 2021 13:46 
 */
public class symp {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static final OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.obolibrary.org/obo/symp.owl/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    
    public static final AnnotationProperty ID = m_model.createAnnotationProperty( "http://www.geneontology.org/formats/oboInOwl#id" );
    
    public static final AnnotationProperty Definition = m_model.createAnnotationProperty( "http://purl.obolibrary.org/obo/IAO_0000115" );
    
    public static final AnnotationProperty prefLabel = m_model.createAnnotationProperty( "http://www.w3.org/2000/01/rdf-schema#label" );
    
    public static final AnnotationProperty hasExactSynonym = m_model.createAnnotationProperty( "http://www.geneontology.org/formats/oboInOwl#hasExactSynonym" );
    
    
    
    /**
     * Declaração das classes necessárias
     */
    
    
    public static final OntClass eyeSymptom = m_model.createClass( "http://purl.obolibrary.org/obo/SYMP_0019163" );
    
    public static final OntClass inflamedEye = m_model.createClass( "http://purl.obolibrary.org/obo/SYMP_0000310" );
    
    public static final OntClass strainEye = m_model.createClass( "http://purl.obolibrary.org/obo/SYMP_0000212" );
    
    
    public static final OntClass pain = m_model.createClass( "http://purl.obolibrary.org/obo/SYMP_0000099" );
    
    public static final OntClass throatPain = m_model.createClass( "http://purl.obolibrary.org/obo/SYMP_0000505" );
    
    public static final OntClass chestPain = m_model.createClass( "http://purl.obolibrary.org/obo/SYMP_0000576" );
    
    
    public static final OntClass noseSymptom = m_model.createClass( "http://purl.obolibrary.org/obo/SYMP_0000388" );
    
    public static final OntClass runnyNose = m_model.createClass( "http://purl.obolibrary.org/obo/SYMP_0000372" );
    
    
    public static final OntClass behavioralSymptom = m_model.createClass( "http://purl.obolibrary.org/obo/SYMP_0019182" );
    
    public static final OntClass irritability = m_model.createClass( "http://purl.obolibrary.org/obo/SYMP_0000654" );
    
    
    public static final OntClass generalSymptom = m_model.createClass( "http://purl.obolibrary.org/obo/SYMP_0000567" );
    
    public static final OntClass inflammation = m_model.createClass( "http://purl.obolibrary.org/obo/SYMP_0000061" );
    
    public static final OntClass respiratoryAbnormality = m_model.createClass( "http://purl.obolibrary.org/obo/SYMP_0000598" );
    
    public static final OntClass wheezing = m_model.createClass( "http://purl.obolibrary.org/obo/SYMP_0000604" );
    
    public static final OntClass dyspnea = m_model.createClass( "http://purl.obolibrary.org/obo/SYMP_0019153" );
    
    public static final OntClass hypoventilation = m_model.createClass( "http://purl.obolibrary.org/obo/SYMP_0000428" );
    
    
    public static final OntClass neurologicalAndPhysiologicalSymptom = m_model.createClass( "http://purl.obolibrary.org/obo/SYMP_0000410" );
    
    public static final OntClass headache = m_model.createClass( "http://purl.obolibrary.org/obo/SYMP_0000504" );
    
    public static final OntClass drowsiness = m_model.createClass( "http://purl.obolibrary.org/obo/SYMP_0000024" );
    
    public static final OntClass fatigue = m_model.createClass( "http://purl.obolibrary.org/obo/SYMP_0019177" );
    
    
    public static final OntClass respiratorySystemAndChestSymptom = m_model.createClass( "http://purl.obolibrary.org/obo/SYMP_0019182" );
    
    public static final OntClass cough = m_model.createClass( "http://purl.obolibrary.org/obo/SYMP_0000514" );
  
    public static final OntClass sneezing = m_model.createClass( "http://purl.obolibrary.org/obo/SYMP_0000139" );
        
}
