package br.ufg.inf.mestrado.hermeswidget.ontologies;
 
import com.hp.hpl.jena.ontology.Individual;
import com.hp.hpl.jena.ontology.OntModel;
import com.hp.hpl.jena.ontology.OntModelSpec;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Resource;
  
/**
 * Vocabulary definitions from unit.ttl 
 * @author Auto-generated by schemagen on 06 nov 2019 14:48 
 */
public class Unit {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static final OntModel M_MODEL = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://qudt.org/2.1/vocab/unit#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );
    
    //Individual http_//qudt.org/schema/qudt/Unit
    public static final Individual Percent = M_MODEL.createIndividual(Qudt.Unit);
    
    //Individual http_//qudt.org/schema/qudt/TemperatureUnit
    public static final Individual DEG_C = M_MODEL.createIndividual(Qudt.TemperatureUnit);
    
    //Individual http_//qudt.org/schema/qudt/PPM
    public static final Individual PPM = M_MODEL.createIndividual(Qudt.DimensionlessUnit);

    //Individual http_//qudt.org/schema/qudt/PPB
    public static final Individual PPB = M_MODEL.createIndividual(Qudt.DimensionlessUnit);
    
}
